### ISSUE TITLE
Script error when generating rig (latest blender from today)

### ISSUE THREAD

**Issue by Mennovandijk** [artellblender/auto_rig#11]
![error](https://user-images.githubusercontent.com/48377680/55394916-c4d3e600-5540-11e9-8f33-2dad52a31e3d.png)
Every time i try to create a rig I get some errors. The generated rig is also too small. (I applied all transformations to the mesh before using ARP)
see the error line at the bottom.

**Comment by artellblender** [comment]
Hello, thanks for reporting the issue. Could you please send the blend file?

**Comment by artellblender** [comment]
Closing the issue, no materials were sent to verify the bug.
