### ISSUE TITLE
NameError: name 'set_eyetargets_distance' is not defined

### ISSUE THREAD

**Issue by killarny** [artellblender/auto_rig#13]
(Using version **3.41.34** in Blender 2.8.)

While editing the limb options of the head in the reference bone rig generated by the smart rigging feature with no facial bones, when I click OK on the limb options dialog, the following traceback happens:

```
Traceback (most recent call last):
  File "C:\Users\killa\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\auto_rig_pro-master\auto_rig.py", line 161, in execute
    set_eyetargets_distance(self.eye_target_dist)
NameError: name 'set_eyetargets_distance' is not defined

location: <unknown location>:-1

```

I assume this is due to having no facial bones present in the rig, and probably is harmless, but thought it was worth pointing out as a minor paper cut.

**Comment by artellblender** [comment]
Thanks for reporting, this will be fixed!
