### ISSUE TITLE
ERROR : object 'cs_arrow_cross" not in view layer 'view layer'

### ISSUE THREAD

**Issue by Marietto2008** [artellblender/auto_rig#14]
Hello,

please check the picture below...it happened while I was trying to setup the facial points. I'm using blender 2.8 and autorig pro version 3.41.24.

![2019-04-30_16-48-24](https://user-images.githubusercontent.com/755339/56971404-729ada80-6b69-11e9-8636-2a78b21aea96.png)

**Comment by artellblender** [comment]
Thanks for reporting, this should be fixed in the latest version.
