### ISSUE TITLE
Unity export deletes animation and does not export animation

### ISSUE THREAD

**Issue by neilford** [artellblender/auto_rig#18]
I have tried exporting an FBX for Unity as Humanoid rig from 2.79b and 2.80. When I try to export a humanoid rig, all the keys in my file are deleted during export. The exported fax does not contain any animation. It was working a week ago. Now, it  is not. Have you seen this before? Thanks.

**Comment by artellblender** [comment]
Hello neilford,
Please check this to export animation:
http://lucky3d.fr/auto-rig-pro/doc/ge_export_doc.html#animations-export

Is this issue still valid?If yes, please send an example blend file to reproduce the bug.

**Comment by artellblender** [comment]
Considering the lack of informations to reproduce the bug, I close the issue for now.
