### ISSUE TITLE
[Export FBX] Error in Unreal: Failed to merge bones

### ISSUE THREAD

**Issue by Swarly1803** [artellblender/auto_rig#27]
The following error occurs when I want to import a rigged mesh into Unreal:
 ![ue4_Error](https://user-images.githubusercontent.com/27783184/65232732-ec5c4200-dad1-11e9-8e98-201968c974ce.JPG)

 The error occurs with version 3.42_11. 
If I use version 3.41_57, the import works fine. 
I used the same settings for the export in both versions.

Thank you.

**Comment by artellblender** [comment]
Thanks for reporting the issue, please send the 2 Fbx files exported with both versions this will help to investigate on it.

**Comment by artellblender** [comment]
Closing the issue since it has been two months without activity

**Comment by artellblender** [comment]
Please see below for support:
http://lucky3d.fr/auto-rig-pro/doc/bug_report.html

Le mar. 4 avr. 2023 à 16:53, Mohsinali7890 ***@***.***> a
écrit :

**Comment by elipeters** [comment]
[follow this](https://docs.readyplayer.me/ready-player-me/integration-guides/unreal-engine/animations/blender-to-unreal-export) worked for me
