### ISSUE TITLE
Report: Error when trying to activate Autorig on blender Mac

### ISSUE THREAD

**Issue by szbz2020** [artellblender/auto_rig#30]
trying to activate Auto-Rig pro for Blender 2.8 on Mac (after installation add-on) and keep getting an error message. See image attracted. 

<img width="665" alt="Screenshot 2020-01-07 at 11 49 44" src="https://user-images.githubusercontent.com/59607595/71894752-071cfa00-3147-11ea-989d-64caa19c8225.png">

**Comment by artellblender** [comment]
This means the Blender 2.79 version is installed, while Blender 2.81 is running the addon. The compatibility is broken with newer version, the latest version must be installed
http://lucky3d.fr/auto-rig-pro/doc/faq.html#the-addon-doesn-t-install
