### ISSUE TITLE
Mike rig export to FBX Unity/Humanoid missing bone controls

### ISSUE THREAD

**Issue by Leteen** [artellblender/auto_rig#31]
Hi!, I recently got this addon for an UpWork project and I can't seem to export a couple animations. Eyebrows and mouth corners aren't binded to the mesh whatsoever, resulting in a really creepy final mesh, I believe its a bug with the exporting since it works properly in blender.

**Comment by artellblender** [comment]
Eyebrows and mouth corners are deformed with shape keys, which are driven by the transforms of the controllers.
