### ISSUE TITLE
Issues fully removing the rig

### ISSUE THREAD

**Issue by dsguffey** [artellblender/auto_rig#35]
So, after getting a result I didn't like with the mouth, I decided to remove the rig and start over from scratch. I selected all and unbound the rig. I deleted it. I deleted all the vertices it created for all the objects. I unparented everything and deleted the armature modifiers just to be safe. I deleted all the actions the in the file viewer. Still, there are left behind "fake" object doubles for everything that was a part of the rig in the view layer of the outliner. Clicking on an object also selects its fake and vice versa. I also can't put a double in the same collection as the original object. This is really annoying me; how do I fix it?

**Comment by artellblender** [comment]
Maybe there was an error when binding, make sure to disable the Debug mode in the addon's preferences.
Please try with the latest version.
