### ISSUE TITLE
Rig picker camera for proxy rigs

### ISSUE THREAD

**Issue by PiOverFour** [artellblender/auto_rig#36]
Hello @artellblender, thanks for this great add-on, TD at Les Fées Spéciales here.

I stumbled upon an issue when trying to use the rig picker. I have my rigs in library files, and I link and proxy them to animate in shots. In this situation, I can’t use the rig picker because the camera is not actually in the scene, but in an instance object. I modified the code this way to fix this:

``` diff
diff --git a/rig_functions.py b/rig_functions.py
index 10148c2..90c605d 100644
--- a/rig_functions.py
+++ b/rig_functions.py
@@ -1136,13 +1136,17 @@ def _set_picker_camera(self):
     current_cam = bpy.context.scene.camera
 
     rig = bpy.data.objects[bpy.context.active_object.name]
-    bpy.ops.object.select_all(action='DESELECT')
     cam_ui = None
     rig_ui = None
     ui_mesh = None
     char_name_text = None
 
-    for child in rig.children:
+    # Proxy rigs
+    if rig.proxy_collection is not None:
+        children = rig.proxy_collection.instance_collection.all_objects
+    else:
+        children = rig.children
+    for child in children:
         if child.type == 'CAMERA' and 'cam_ui' in child.name:
             cam_ui = child
         if child.type == 'EMPTY' and 'rig_ui' in child.name:
@@ -1176,14 +1180,13 @@ def _set_picker_camera(self):
             except:
                 pass
 
-    set_active_object(active_obj_name)
-
     if cam_ui:
         # lock the camera transforms
         #cam_ui.lock_location[0]=cam_ui.lock_location[1]=cam_ui.lock_location[2]=cam_ui.lock_rotation[0]=cam_ui.lock_rotation[1]=cam_ui.lock_rotation[2] = True
-        cam_ui.select_set(state=1)
-        bpy.context.view_layer.objects.active = cam_ui
-        bpy.ops.view3d.object_as_camera()
+
+        bpy.context.space_data.use_local_camera = True
+        bpy.context.space_data.camera = cam_ui
+        bpy.context.space_data.region_3d.view_perspective = "CAMERA"
 
         # set viewport display options
         #bpy.context.space_data.lock_camera_and_layers = False
@@ -1230,9 +1233,6 @@ def _set_picker_camera(self):
             cam_ui.data.clip_end = dist*1.1
             cam_ui.data.ortho_scale = fac_ortho * picker_size
 
-        #restore the scene camera
-        bpy.context.scene.camera = current_cam
-
     else:
         self.report({'ERROR'}, 'No picker camera found for this rig')
 
```

I couldn’t open a pull request since the add-on is stored as a zip, so I hope this will be useful to you…

**Comment by PiOverFour** [comment]
> ça a fonctionné sans problème a condition de bien créer le proxy camera avant de cliquer le bouton "Set Picker Cam" ):

Aaaah bien sûr, c’est logique ! En fait un animateur m’a demandé comment ça marchait et plutôt que de lire la doc j’ai bricolé le code. :facepalm:

Je connaissais X-Pose picker, Pascal avait commencé à le mettre en prod mais pour des raisons de distribution (je crois), on a décidé de s’en passer. Je ne me souviens plus bien de toute l’affaire, en tout cas en utilisant le patch que je t’envoie, ça semble répondre aux attentes des équipes d’animation. :)

À plus,
Damien

**Comment by artellblender** [comment]
Ok, merci pour le patch ça semble fonctionner!
Par contre ça ne fonctionne pas quand on désactive "Instance Collections" au moment de faire le link. Dans ce cas il faut quand même faire un proxy de la cam_ui et la parenter au proxy du rig. 
Mais si "Instance Collections" est activé (par défaut), ça évite au moins cette manip, merci du coup. Il y a peut être moyen de le faire fonctionner quand "Instance Collections" est désactivé, je chercherai à l'occasion.
J'intègre tes modifs dans le version officielle, merci.

**Comment by PiOverFour** [comment]
Super !

Pour notre usage Instance Collections est toujours activé, donc effectivement ça fait ça en moins à faire.

Merci, je ferme :)
