### ISSUE TITLE
FBX exporter

### ISSUE THREAD

**Issue by Rafflin** [artellblender/auto_rig#5]
Greetings! 

First want to say that your rigging addon is great!

However, I am getting a bug when trying to export an FBX file in Blender 2.8.  I am trying to export to a Unity Humanoid.  The Unity Generic works but the bone hierarchy is screwed up.
If you need other files to diagnose, let me know.
shunaka@comcast.net

I have attached a screenshot of the error generated.
![2 8 export bug](https://user-images.githubusercontent.com/20730630/52168740-940f3600-26e2-11e9-950e-1d178202390e.PNG)

**Comment by artellblender** [comment]
Thanks for the report, it's fixed in the current version. Will publish it soon :)
