### ISSUE TITLE
Blender 2.8: Error on FBX export to UE4

### ISSUE THREAD

**Issue by SheepShanker** [artellblender/auto_rig#6]
[ARP_Bug_FBX_UE4.zip](https://github.com/artellblender/auto_rig/files/2839932/ARP_Bug_FBX_UE4.zip)
Here's a zipfile with the .blend file and the log, as well as some screenshots.

Love the addon, it's magic! The smart rig just blew my mind, rigged that character in around ~5 minutes, just needs a few tweaks on the weighting. Awesome stuff man. Let me know if this is the optimal way to report bugs. :)

**Comment by artellblender** [comment]
Thanks for reporting, it's now fixed in the 3.41.19 version.
