### ISSUE TITLE
Undo function not working ?

### ISSUE THREAD

**Issue by ga34rul** [artellblender/auto_rig#8]
Using Blender 2.79, when pressing ctrl+z actions wont be undone. It seems that this happens during weight painting and when playing around in the pose mode. But apart from that, ARP is really really awesome!

**Comment by artellblender** [comment]
It seems to be a Blender bug/limitation, sometimes the Undo gets disabled when, I assume, the RAM is overloaded. To enable it back, go to the User Preferences > Editing tab.
