### ISSUE TITLE
Feature Request: Generic Bone Chains

### ISSUE THREAD

**Issue by jlamarche** [artellblender/auto_rig#9]
Auto Rig is really amazing, but for many characters, the add limb options are a bit limited. Having the ability to add a generic bone chain that's not a leg/arm/spine/tail and that could be parented to any bone, would be hugely helpful. I was recently trying to rig a character with multiple ponytails. I had some success with the first pony tail by adding a tail and then re-parenting the tail to the character's head, but "duplicate" wasn't available for the tail chain, and manually duplicating it broke the "apply rig" option. After a fair amount of playing, I haven't found a good way to do this other than to rig manually, which breaks some of the nice features of the rig (like Edit Reference Bones).

Thanks!

**Comment by artellblender** [comment]
Hello, thanks for the input.
Only built-in limbs can be duplicated/disabled using the dedicated buttons, if you create your own set of bones over the rig (the ponytail) you can duplicate it or remove it manually, it does not break anything.

**Comment by jlamarche** [comment]
If you create bone chains manually, can you still use `Edit Reference Bones` and `Match to Rig` functionality? If so, that's awesome.

**Comment by artellblender** [comment]
Yes of course, additional bones won't interfere with it. However no reference bones can be created for them, they will remain on the final generated rig.
